# Generated by Django 4.2.4 on 2023-08-21 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_record_created_at_alter_record_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='created_at',
            new_name='created',
        ),
    ]
