# Generated by Django 4.2.4 on 2023-08-21 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_record_created_record_made_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='made_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
